### ISSUE TITLE
Querying original argv doesn't work with Python 3.8

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#2206]
```
Traceback (most recent call last):
  File "C:\python_stuff\thonny\thonny\__init__.py", line 392, in get_orig_argv
    from sys import orig_argv  # since 3.10
ImportError: cannot import name 'orig_argv' from 'sys' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\python_stuff\thonny\thonny\__main__.py", line 4, in <module>
    launch()
  File "C:\python_stuff\thonny\thonny\__init__.py", line 223, in launch
    _configure_frontend_logging()
  File "C:\python_stuff\thonny\thonny\__init__.py", line 375, in _configure_frontend_logging
    _configure_logging(get_frontend_log_file(), _choose_logging_level())
  File "C:\python_stuff\thonny\thonny\__init__.py", line 440, in _configure_logging
    main_logger.info("original argv: %s", get_orig_argv())
  File "C:\python_stuff\thonny\thonny\__init__.py", line 401, in get_orig_argv
    ctypes.pythonapi.Py_GetArgcArgv(ctypes.byref(argc), ctypes.byref(argv))
  File "C:\Python38-32\lib\ctypes\__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python38-32\lib\ctypes\__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'Py_GetArgcArgv' not found

Process finished with exit code 1
```
