### ISSUE TITLE
Error in Debug mode (DebuggerResponse)

### ISSUE THREAD

**Issue by aivarannamaa** [thonny/thonny#570]
**[Original report](https://bitbucket.org/bitbucket-issue-migration\thonny-issues.zip/issue/570) by Anonymous.**

----------------------------------------

Hello,

With 3.0.1 and 3.0.3 same problem happens.

Even when using simple "Hello World" programm, "Run" is fine, 
but "Debug nicer" and "Debug faster" show:
'DebuggerResponse' object has no attribute 'sequence'

When upgraded to 3.0.3 error did not show up immediately, but came after palying
around with debug/breakpoinst/ etc..
